const CONFIG = {
    introTitle: 'Cu à!',
    introDesc: `hà lô không có gì đâu mà xem :3`,
    btnIntro: 'lêu lêu',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 😙',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'kkkk',
    btnNo: 'Không, Anh trai à :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'sát',
    mess: 'hù',
    messDesc: 'yêu a mãi nhé.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'firework.html' ,
    bum: 'Bùm',
}
