const CONFIG = {
    bum: 'Cu à!',
    bum: `hà lô không có gì đâu mà xem :3`,
    bum: 'lêu lêu',
    bum: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 😙',
    bum: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    bum: 'kkkk',
    bumbum: 'Không, Anh trai à :3',
    bum:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    bum: 'Gửi cho anh <3',
    bum: 'sát',
    bum: 'hù',
    bum: 'yêu a mãi nhé.',
    bum: 'Okiiiii lun <3',
    bum: 'firework.html' ,
    bum: 'Bùm',
}
